name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build:
    runs-on: self-hosted  # Use self-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Hugo
        run: sudo apt-get install hugo

      - name: Build Hugo site
        run: hugo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./public